#!/bin/sh
# Date: Feb.12, 2022
# The scripts makes a soft link for a given file
# and removes its dextension if there are any.

FILE_NAME=$1
# Remove any extensions, such as ".sh"
FILE_WITHOUT_EXT=${FILE_NAME%.*}

ln -s $FILE_NAME $FILE_WITHOUT_EXT
