#!/bin/sh

#: Written by KFH: karshi.hasanov@utoronto.ca
#: KFH Systems Inc.
#: Date: Feb.5, 2019
#: Description: This code mounts/umounts the external storage.
#               The name of the device is "My_Book_Pro".
#              -If the device is mounted alread, it umounts and wise verse.
#              -No options needed to pass. Just run as it is.

# First we want to check if the disk is already mounted or not:
t=`df | grep -i my_book_pro`

# If if does, the exit code will be 0 otherwise any other number
n=$?
if [ $n -eq 0 ]; then
	echo "The devise is mounted"
	echo "...unmounting the device"
	sudo diskutil umount /Volumes/My_Book_Pro

else
	echo "The device was NOT mounted!!!"
	echo "...mounting the device"
	slice=`diskutil list | grep -i my_book_pro | awk '{print $(NF)}'`
	sudo diskutil mount /dev/$slice
fi
