#!/bin/sh
cd /Users/khasanov/Library/'Application Support'/com.evernote.Evernote
git status
git add .
git commit -m "Just updated the Evernotes"
if [ "$1" == "-u" ]
then
git push -u origin master
fi

