#!/bin/bash

# The program uses the "tmutil" utility
# For more info, read "tmutil help"
if [ $1 ]
	then
	backup_file=$1	
	# remove any empty space
        backup_file=$(echo $backup_file | tr -d ' ')
	sudo tmutil delete $backup_file
else
	echo 'Usage: => delete_backup /path/to/snapshot/file'
fi	

