#!/bin/sh
# Written by Karshi Hasanov
# Last modified : October 23, 2015
if [ -z ${1} ] || [ ${1} = "-h" ] || [ ${1} = "--help" ]
	then
	     echo "
	     Usage: => modify <alias name>
	     Example: To modify the Apache config file. you can issue
	              the following command
		      => modify httpd.conf
		      => modify apache 
		      => modify http

		      # alias -> vim /usr/local/etc/apache24/httpd.conf
             To see the aliases: => modify --show -aliases 
	                         => modify -sa
	     "
             exit 1
fi

if [ ${1} = "--show-aliases" ] || [ ${1} = "-sa" ]
	then
	     echo "
	     # Apache Server Config File :
	     httpd.conf --> /usr/local/etc/apache24/httpd.conf
	     Aliases: apache, http, httpd and httpd.conf

             # Apache Server Virtual Hosts Config File:
	     httpd-vhosts.conf --> /usr/local/etc/apache24/extra/httpd-vhosts.conf
             Aliases: vhosts, virtual-hosts, vh, vhosts.conf ,and httpd-vhosts.conf

	     # Apache Server SSL Support for Virtual Hosts
	     httpd-ssl.conf --> /usr/local/etc/apache24/extra/httpd-ssl.conf
	     Aliases: vhost-ssl, httpd-ssl, http-ssl and httpd-ssl.conf

	     # PHP main configuration file: php.ini - responsible for PHP's behavior.
	     php.ini --> /usr/local/etc/php.ini
	     Aliases: php.ini, phpconf,viphp

	     # Nginx Server
	     nginx.conf --> /usr/local/etc/namedb/nginx.conf
	     Aliases: nginx.conf, nginx

	     "
fi

		      
check ()
	{
	   if [ "$(id -u)" != "0" ]; then
		echo " ---> The program requires the root privileges"
	        exit 1
           fi
   }

case "${1}" in
    
	"httpd.conf"|"apache"|"http"|"httpd")
		check && sudo vim /usr/local/etc/apache24/httpd.conf;;
	"httpd-vhosts.conf"|"vhosts.conf"|"vhosts"|"virtual-hosts"|"vh")
		check && sudo vim /usr/local/etc/apache24/extra/httpd-vhosts.conf;;
	"httpd-ssl.conf"|"vhost-ssl"|"httpd-ssl"|"http-ssl")
		check && sudo vim /usr/local/etc/apache24/extra/httpd-ssl.conf;;
	"php.ini"|"phpconf"|"viphp")
		check && sudo vim /usr/local/etc/php.ini;;
	"nginx.conf"|"nginx")
		check && sudo vim /usr/local/etc/nginx/nginx.conf;;
	
	
esac

	 
