#!/bin/sh
# Format: Day/Month/Year  Hour/Minute/Second
DATE_TIME=$(date "+DATE: %d/%m/%Y TIME: %H:%M:%S")
SRC_DIR="/Volumes/My_Book_Pro/KFH/KFH_Audio-Video"
DEST_DIR="/Volumes/DC_Audio-Video"
LOG_DIR="/Volumes/DC_Log"
LOG_FILE="${LOG_DIR}/DC_Log.log"
RSYNC_DIR="/usr/bin"

echo "Removing '.DC_Store' from the ${SRC_DIR}"
find ${SRC_DIR} -name .DC_Store -exec rm '{}' \;
echo "...done!"

echo "...mounting to DC_Main"
if (!(mount | grep ${DEST_DIR})); then
	echo "Error: The ${DEST_DIR} is NOT mounted !"
	echo "Audio-Video : FAILED	${DATE_TIME}" >> ${LOG_FILE}
	exit 1
else
	${RSYNC_DIR}/rsync -avz --no-perms --omit-dir-times ${SRC_DIR}/ ${DEST_DIR}
	echo "Audio-Video : SUCCESS	${DATE_TIME}" >> ${LOG_FILE}
	
	echo "Removing '.DC_Store' from the ${DEST_DIR}"
	find ${DEST_DIR} -name .DC_Store -exec rm '{}' \;
	echo "...done!"

	exit 0
fi

