#!/bin/sh
# Format: Day/Month/Year  Hour/Minute/Second
DATE_TIME=$(date "+DATE: %d/%m/%Y TIME: %H:%M:%S")
SRC_DIR="/Volumes/My_Book_Pro/KFH/KFH_Main"
DEST_DIR="/Volumes/DC_Main"
LOG_DIR="/Volumes/DC_Log"
LOG_FILE="${LOG_DIR}/DC_Log.log"
RSYNC_DIR="/usr/bin"

# First, weed to remove the ".DC_Store" files
# These files created by the MAC OS X.
echo "Removing '.DC_Store' from  ${SRC_DIR}"
find ${SRC_DIR} -name .DC_Store -exec rm '{}' \;
echo "...done!"

echo "...mounting to DC_Main"
if (!(mount | grep ${DEST_DIR})); then
	echo "Error: The ${DEST_DIR} is NOT mounted !"
	echo "Main : FAILED		${DATE_TIME}" >> ${LOG_FILE}
	exit 1
else
	${RSYNC_DIR}/rsync -avz --no-perms --omit-dir-times ${SRC_DIR}/ ${DEST_DIR}
	echo "Removing '.DC_Store' files from ${DEST_DIR}" 
	echo "Main : SUCCESS		${DATE_TIME}" >> ${LOG_FILE}
	exit 0
fi

