#!/bin/sh
# Written by Karshi
# Date: May, 2014

TOMCAT_DIR="/Users/khasanov/Dev-Software/Tomcat/apache-tomcat-7.0.47"

usage ()
{
	echo "Usage: => tomcat start ( to start the Tomcat server )"
	echo "       => tomcat stop ( to stop the server)"
}

start_srv ()
{
	
	netstat -an | grep 8080
	OUT=`echo $?`
	if [ ${OUT} == 0 ]; then
		echo "Looks like the Tomcat instance is already running"
		exit 1
	else
		echo "...Starting the Tomcat instance"
		${TOMCAT_DIR}/bin/startup.sh
	fi
}

stop_srv ()
{
        netstat -an | grep 8080
	OUT=`echo $?`
	if [ ${OUT} != 0 ]; then
		echo "No the Tomcat server instance found !"
		exit 1
	else
		echo "...shutting down the Tomcat instance"
		${TOMCAT_DIR}/bin/shutdown.sh

	fi
}

# If no argument or more than one arguments
if [ $# -eq 0 ] || [ $# -gt 1 ]; then
	usage; exit 1
fi

case "${1}" in
	"start")
		start_srv ;;
	"stop")
		stop_srv ;;
	"*")
		usage ;;
esac

