#!/bin/bash
echo "...umounting the 'Main'"
sudo umount /Volumes/DC_Main

echo "...umounting the 'Library'"
sudo umount /Volumes/DC_Library

echo "...umounting the 'Projects'"
sudo umount /Volumes/DC_Projects

echo "...umounting the 'Training'"
sudo umount /Volumes/DC_Training

echo "...umounting the 'Log'"
sudo umount /Volumes/DC_Log
