#!/bin/bash

# The program uses the "tmutil" utility
# For more info, read "tmutil help"
if [ $1 ]
	then
	backup_file=$1	
	# Remove any empty space
        #backup_file=$(echo $backup_file | tr -d ' ')
	
        # Replace any empty space with "\ "
        backup_file="$(echo $backup_file | sed 's/ /\ /g')"
        sudo tmutil delete $backup_file
else
	echo 'Usage: => delete_single_backup /path/to/snapshot/file'
fi	

